ALTER TABLE metrics
    ADD COLUMN IF NOT EXISTS unit_amount_minor BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS currency TEXT NOT NULL DEFAULT 'usd';

ALTER TABLE rollups
    ADD COLUMN IF NOT EXISTS stripe_item_id TEXT NOT NULL DEFAULT '';
